[package]
name = "aocleaders"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4"
reqwest = { version = "0.10", features = ["json"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros"] }
rocket = "0.4"
config = "0.10"
log = "0.4"
env_logger = "0.8"