# By default, Rocket applications run in the development environment for debug
# builds and the production environment for non-debug builds. The environment
# can be changed via the ROCKET_ENV environment variable.

[development]
address = "localhost"
port = 8000
# workers = 4

[staging]
address = "0.0.0.0"
port = 8000
# workers = 16

[production]
address = "0.0.0.0"
port = 8000
# workers = 16