# Leaderboard name
leaderboard_name = "me and my friends"

# IDs of all Advent of Code leaderboards to be merged
leaderboard_ids = [12345, 23456]

# Default leaderboard order: "local_score" (default) or "stars"
# leaderboard_default_order = "stars"

# Session cookie for adventofcode.com (with access to all leaderboards)
session_cookie = "session=xxxx..."

# How often to fetch leaderboards from adventofcode.com, in seconds
# (default: 900)
# leaderboard_update_sec = 1200

# Override the latest event year, which by default is the current year or the
# previous year if current date is before Dec 1st (when first puzzle unlocks)
# latest_event_year = 2020
